#ifndef GENSERIAL_MODELINFO_AUTOGEN_H
#define GENSERIAL_MODELINFO_AUTOGEN_H

// DO NOT EDIT! This is an autogenerated file.

#include "macserial.h"

typedef enum {
  MacBook1_1, // Intel Core Duo T2400 @ 1.83 GHz
  MacBook10_1, // Intel Core m3-7Y32 @ 1.10 GHz
  MacBook2_1, // Intel Core 2 Duo T5600 @ 1.83 GHz
  MacBook3_1, // Intel Core 2 Duo T7500 @ 2.20 GHz
  MacBook4_1, // Intel Core 2 Duo T8300 @ 2.40 GHz
  MacBook5_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  MacBook5_2, // Intel Core 2 Duo P7450 @ 2.13 GHz
  MacBook6_1, // Intel Core 2 Duo P7550 @ 2.26 GHz
  MacBook7_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  MacBook8_1, // Intel Core M 5Y51 @ 1.10 GHz
  MacBook9_1, // Intel Core m3-6Y30 @ 1.10 GHz
  MacBookAir1_1, // Intel Core 2 Duo P7500 @ 1.60 GHz
  MacBookAir2_1, // Intel Core 2 Duo SL9600 @ 2.13 GHz
  MacBookAir3_1, // Intel Core 2 Duo SU9400 @ 1.40 GHz
  MacBookAir3_2, // Intel Core 2 Duo SL9400 @ 1.86 GHz
  MacBookAir4_1, // Intel Core i5-2467M @ 1.60 GHz
  MacBookAir4_2, // Intel Core i5-2557M @ 1.70 GHz
  MacBookAir5_1, // Intel Core i5-3317U @ 1.70 GHz
  MacBookAir5_2, // Intel Core i5-3317U @ 1.70GHz
  MacBookAir6_1, // Intel Core i5-4250U @ 1.30 GHz
  MacBookAir6_2, // Intel Core i5-4250U @ 1.30 GHz
  MacBookAir7_1, // Intel Core i5-5250U @ 1.60 GHz
  MacBookAir7_2, // Intel Core i5-5250U @ 1.60 GHz
  MacBookAir8_1, // Intel Core i5-8210Y @ 1.60 GHz
  MacBookAir8_2, // Intel Core i5-8210Y @ 1.60 GHz
  MacBookPro1_1, // Intel Core Duo L2400 @ 1.66 GHz
  MacBookPro1_2, // Intel Core Duo T2600 @ 2.16 GHz
  MacBookPro10_1, // Intel Core i7-3615QM @ 2.30 GHz
  MacBookPro10_2, // Intel Core i5-3210M @ 2.50 GHz
  MacBookPro11_1, // Intel Core i5-4258U @ 2.40 GHz
  MacBookPro11_2, // Intel Core i7-4770HQ @ 2.20 GHz
  MacBookPro11_3, // Intel Core i7-4850HQ @ 2.30 GHz
  MacBookPro11_4, // Intel Core i7-4770HQ @ 2.20 GHz
  MacBookPro11_5, // Intel Core i7-4870HQ @ 2.50 GHz
  MacBookPro12_1, // Intel Core i5-5257U @ 2.70 GHz
  MacBookPro13_1, // Intel Core i5-6360U @ 2.00 GHz
  MacBookPro13_2, // Intel Core i7-6567U @ 3.30 GHz
  MacBookPro13_3, // Intel Core i7-6700HQ @ 2.60 GHz
  MacBookPro14_1, // Intel Core i5-7360U @ 2.30 GHz
  MacBookPro14_2, // Intel Core i5-7267U @ 3.10 GHz
  MacBookPro14_3, // Intel Core i7-7700HQ @ 2.80 GHz
  MacBookPro15_1, // Intel Core i7-8750H @ 2.20 GHz
  MacBookPro15_2, // Intel Core i7-8559U @ 2.70 GHz
  MacBookPro15_3, // Intel Core i7-8850H @ 2.60 GHz
  MacBookPro15_4, // Intel Core i5-8257U @ 1.40 GHz
  MacBookPro2_1, // Intel Core 2 Duo T7600 @ 2.33 GHz
  MacBookPro2_2, // Intel Core 2 Duo T7400 @ 2.16 GHz
  MacBookPro3_1, // Intel Core 2 Duo T7700 @ 2.40 GHz
  MacBookPro4_1, // Intel Core 2 Duo T8300 @ 2.40 GHz
  MacBookPro5_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  MacBookPro5_2, // Intel Core 2 Duo T9600 @ 2.80 GHz
  MacBookPro5_3, // Intel Core 2 Duo P8800 @ 2.66 GHz
  MacBookPro5_4, // Intel Core 2 Duo P8700 @ 2.53 GHz
  MacBookPro5_5, // Intel Core 2 Duo P7550 @ 2.26 GHz
  MacBookPro6_1, // Intel Core i5-540M @ 2.53 GHz
  MacBookPro6_2, // Intel Core i5-520M @ 2.40 GHz
  MacBookPro7_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  MacBookPro8_1, // Intel Core i5-2415M @ 2.30 GHz
  MacBookPro8_2, // Intel Core i7-2675QM @ 2.20 GHz
  MacBookPro8_3, // Intel Core i7-2820QM @ 2.30 GHz
  MacBookPro9_1, // Intel Core i7-3615QM @ 2.30 GHz
  MacBookPro9_2, // Intel Core i5-3210M @ 2.50 GHz
  MacPro1_1, // Intel Core Xeon 5130 x2 @ 2.00 GHz
  MacPro2_1, // Intel Xeon X5365 x2 @ 3.00 GHz
  MacPro3_1, // Intel Xeon E5462 x2 @ 2.80 GHz
  MacPro4_1, // Intel Xeon W3520 @ 2.66 GHz
  MacPro5_1, // Intel Xeon W3530 @ 2.80 GHz
  MacPro6_1, // Intel Xeon E5-1620 v2 @ 3.70 GHz
  MacPro7_1, // Intel Xeon W-3245M CPU @ 3.20 GHz
  Macmini1_1, // Intel Core Solo T1200 @ 1.50 GHz
  Macmini2_1, // Intel Core 2 Duo T5600 @ 1.83 GHz
  Macmini3_1, // Intel Core 2 Duo P7350 @ 2.00 GHz
  Macmini4_1, // Intel Core 2 Duo P8600 @ 2.40 GHz
  Macmini5_1, // Intel Core i5-2415M @ 2.30 GHz
  Macmini5_2, // Intel Core i5-2520M @ 2.50 GHz
  Macmini5_3, // Intel Core i7-2635QM @ 2.00 GHz
  Macmini6_1, // Intel Core i5-3210M @ 2.50 GHz
  Macmini6_2, // Intel Core i7-3615QM @ 2.30 GHz
  Macmini7_1, // Intel Core i5-4260U @ 1.40 GHz
  Macmini8_1, // Intel Core i7-8700B @ 3.20 GHz
  Xserve1_1, // Intel Xeon 5130 x2 @ 2.00 GHz
  Xserve2_1, // Intel Xeon E5462 x2 @ 2.80 GHz
  Xserve3_1, // Intel Xeon E5520 x2 @ 2.26 GHz
  iMac10_1, // Intel Core 2 Duo E7600 @ 3.06 GHz
  iMac11_1, // Intel Core i5-750 @ 2.66 GHz
  iMac11_2, // Intel Core i3-540 @ 3.06 GHz
  iMac11_3, // Intel Core i5-760 @ 2.80 GHz
  iMac12_1, // Intel Core i5-2400S @ 2.50 GHz
  iMac12_2, // Intel Core i7-2600 @ 3.40 GHz
  iMac13_1, // Intel Core i7-3770S @ 3.10 GHz
  iMac13_2, // Intel Core i5-3470S @ 2.90 GHz
  iMac13_3, // Intel Core i5-3470S @ 2.90 GHz
  iMac14_1, // Intel Core i5-4570R @ 2.70 GHz
  iMac14_2, // Intel Core i7-4771 @ 3.50 GHz
  iMac14_3, // Intel Core i5-4570S @ 2.90 GHz
  iMac14_4, // Intel Core i5-4260U @ 1.40 GHz
  iMac15_1, // Intel Core i7-4790k @ 4.00 GHz
  iMac16_1, // Intel Core i5-5250U @ 1.60 GHz
  iMac16_2, // Intel Core i5-5675R @ 3.10 GHz
  iMac17_1, // Intel Core i5-6500 @ 3.20 GHz
  iMac18_1, // Intel Core i5-7360U @ 2.30 GHz
  iMac18_2, // Intel Core i5-7400 @ 3.00 GHz
  iMac18_3, // Intel Core i5-7600k @ 3.80 GHz
  iMac19_1, // Intel Core i9-9900K @ 3.60 GHz
  iMac19_2, // Intel Core i5-8500 @ 3.00 GHz
  iMac4_1, // Intel Core Duo T2400 @ 1.83 GHz
  iMac4_2, // Intel Core Duo T2400 @ 1.83 GHz
  iMac5_1, // Intel Core 2 Duo T7200 @ 2.00 GHz
  iMac5_2, // Intel Core 2 Duo T5600 @ 1.83 GHz
  iMac6_1, // Intel Core 2 Duo T7400 @ 2.16 GHz
  iMac7_1, // Intel Core 2 Duo T7300 @ 2.00 GHz
  iMac8_1, // Intel Core 2 Duo E8435 @ 3.06 GHz
  iMac9_1, // Intel Core 2 Duo E8135 @ 2.66 GHz
  iMacPro1_1, // Intel Xeon W-2140B CPU @ 3.20 GHz
} AppleModel;

#define APPLE_MODEL_MAX 114

static PLATFORMDATA ApplePlatformData[] = {
  { "MacBook1,1", "W80A041AU9B" },
  { "MacBook10,1", "C02TQHACHH27" },
  { "MacBook2,1", "W88A041AWGP" },
  { "MacBook3,1", "W8747HACZ66" },
  { "MacBook4,1", "W88A041A0P0" },
  { "MacBook5,1", "W8944T1S1AQ" },
  { "MacBook5,2", "W88AAAAA9GU" },
  { "MacBook6,1", "451131JCGAY" },
  { "MacBook7,1", "451211MEF5X" },
  { "MacBook8,1", "C02RCE58GCN3" },
  { "MacBook9,1", "C02RM408HDNK" },
  { "MacBookAir1,1", "W864947A18X" },
  { "MacBookAir2,1", "W86494769A7" },
  { "MacBookAir3,1", "C02FLHACD0QX" },
  { "MacBookAir3,2", "C02DRHACDDR3" },
  { "MacBookAir4,1", "C02KGHACDJY8" },
  { "MacBookAir4,2", "C02GLHACDJWT" },
  { "MacBookAir5,1", "C02J6HACDRV6" },
  { "MacBookAir5,2", "C02HRJXWDRVC" },
  { "MacBookAir6,1", "C02KTHACF5NT" },
  { "MacBookAir6,2", "C02HACKUF5V7" },
  { "MacBookAir7,1", "C02PCLGFGFWK" },
  { "MacBookAir7,2", "C02Q1HACG940" },
  { "MacBookAir8,1", "C02XG1D8JK78" },
  { "MacBookAir8,2", "FVFYR22KLYWM" },
  { "MacBookPro1,1", "W884857JVJ1" },
  { "MacBookPro1,2", "W8629HACTHY" },
  { "MacBookPro10,1", "C02J40Y8F51R" },
  { "MacBookPro10,2", "C02JJ70ADR53" },
  { "MacBookPro11,1", "C02LSHACFH00" },
  { "MacBookPro11,2", "C02LSHACG86R" },
  { "MacBookPro11,3", "C02LSHACFR1M" },
  { "MacBookPro11,4", "C02SNHACG8WN" },
  { "MacBookPro11,5", "C02LSHACG85Y" },
  { "MacBookPro12,1", "C02Q51OSH1DP" },
  { "MacBookPro13,1", "C17SJ18EGVC1" },
  { "MacBookPro13,2", "C02SLHACGYFH" },
  { "MacBookPro13,3", "C02T6L42GTFL" },
  { "MacBookPro14,1", "C02TNHACHV29" },
  { "MacBookPro14,2", "C02TQHACHV2N" },
  { "MacBookPro14,3", "C02TQHACHTD5" },
  { "MacBookPro15,1", "C02X846JJG5J" },
  { "MacBookPro15,2", "C02X141CJHCC" },
  { "MacBookPro15,3", "C02YV0ECLVCG" },
  { "MacBookPro15,4", "FVFYV019L40Y" },
  { "MacBookPro2,1", "W88130WUW0H" },
  { "MacBookPro2,2", "W8827B4CW0L" },
  { "MacBookPro3,1", "W8841OHZX91" },
  { "MacBookPro4,1", "W88484F2YP4" },
  { "MacBookPro5,1", "W88439FE1G0" },
  { "MacBookPro5,2", "W8908HAC2QP" },
  { "MacBookPro5,3", "W8035TG97XK" },
  { "MacBookPro5,4", "W8948HAC7XJ" },
  { "MacBookPro5,5", "W8035TG966D" },
  { "MacBookPro6,1", "C02G5834DC79" },
  { "MacBookPro6,2", "CK132A91AGW" },
  { "MacBookPro7,1", "CK145C7NATM" },
  { "MacBookPro8,1", "W89F9196DH2G" },
  { "MacBookPro8,2", "C02HL0FGDF8X" },
  { "MacBookPro8,3", "W88F9CDEDF93" },
  { "MacBookPro9,1", "C02LW984F1G4" },
  { "MacBookPro9,2", "C02HA041DTY3" },
  { "MacPro1,1", "W88A7HACUQ2" },
  { "MacPro2,1", "W8930518UPZ" },
  { "MacPro3,1", "W88A77AA5J4" },
  { "MacPro4,1", "CT942NZP20H" },
  { "MacPro5,1", "H02380NSEUH" },
  { "MacPro6,1", "F5KLA770F9VM" },
  { "MacPro7,1", "000000000000" },
  { "Macmini1,1", "W8702N1JU35" },
  { "Macmini2,1", "W8705W9LYL2" },
  { "Macmini3,1", "W8905BBE19X" },
  { "Macmini4,1", "C02FHBBEDD6H" },
  { "Macmini5,1", "C07GA041DJD0" },
  { "Macmini5,2", "C07HVHACDJD1" },
  { "Macmini5,3", "C07GWHACDKDJ" },
  { "Macmini6,1", "C07JNHACDY3H" },
  { "Macmini6,2", "C07JD041DWYN" },
  { "Macmini7,1", "C02NN7NHG1J0" },
  { "Macmini8,1", "C07XL9WEJYVX" },
  { "Xserve1,1", "CK703E1EV2Q" },
  { "Xserve2,1", "CK830DLQX8S" },
  { "Xserve3,1", "CK933YJ16HS" },
  { "iMac10,1", "W80AA98A5PE" },
  { "iMac11,1", "G8942B1V5PJ" },
  { "iMac11,2", "W8034342DB7" },
  { "iMac11,3", "QP0312PBDNR" },
  { "iMac12,1", "W80CF65ADHJF" },
  { "iMac12,2", "W88GG136DHJQ" },
  { "iMac13,1", "C02JA041DNCT" },
  { "iMac13,2", "C02JB041DNCW" },
  { "iMac13,3", "C02KVHACFFYW" },
  { "iMac14,1", "D25LHACKF8J2" },
  { "iMac14,2", "D25LHACKF8JC" },
  { "iMac14,3", "D25LHACKF8J3" },
  { "iMac14,4", "D25LHACKFY0T" },
  { "iMac15,1", "C02Q6HACFY10" },
  { "iMac16,1", "C02QQHACGF1J" },
  { "iMac16,2", "C02PNHACGG7G" },
  { "iMac17,1", "C02QFHACGG7L" },
  { "iMac18,1", "C02TDHACH7JY" },
  { "iMac18,2", "C02TDHACJ1G5" },
  { "iMac18,3", "C02TDHACJ1GJ" },
  { "iMac19,1", "C02Y90H3JV3Q" },
  { "iMac19,2", "C02Y93YXJWDX" },
  { "iMac4,1", "W8608HACU2P" },
  { "iMac4,2", "W8627HACV2H" },
  { "iMac5,1", "CK637HACX1A" },
  { "iMac5,2", "W8716HACWH5" },
  { "iMac6,1", "W8652HACVGN" },
  { "iMac7,1", "W8741HACX87" },
  { "iMac8,1", "W8755HAC2E2" },
  { "iMac9,1", "W89A00A36MJ" },
  { "iMacPro1,1", "C02VV5RFHX87" },
};

#define APPLE_MODEL_CODE_MAX 81
static const char *AppleModelCode[][APPLE_MODEL_CODE_MAX] = {
  /* MacBook1,1     */ {"U9B"},
  /* MacBook10,1    */ {"HH27", "HH25", "J9XD", "JPXQ", "JPXN", "J64G", "J64J", "J65G", "J64H", "HH22", "HH23", "HH21", "HH26", "HH24", "HH28", "HH29", "HH2C", "HH2F", "HH2G", "HH2D", "HH2J", "HH2K", "HH2H", "JPXP", "JPXM"},
  /* MacBook2,1     */ {"WGP"},
  /* MacBook3,1     */ {"Z66", "0NH", "0NE", "0NG", "0NF", "0U4", "0WR", "0Z4", "0Z3", "0TZ", "0TY", "0TX", "0TW", "034", "0S8", "0S0", "0S7", "0HC", "0HB", "02Z", "01P", "01V", "01X", "01Z", "0PC", "0PG", "0PB"},
  /* MacBook4,1     */ {"0P0", "27H", "27J", "3N9", "3NF", "3ND", "3NE", "3NA", "3X6", "4R8", "4R7", "385", "47Z", "0P4", "1PX", "1Q7", "1Q2", "1QE", "1QA", "1QB", "28C", "28E", "28D", "0P1", "0P6", "0P5", "0P2", "1LX", "1ZY", "7XD", "6M1", "6ES", "6YP", "5HU", "5HS", "6LM", "6LL", "5AQ", "67C", "3VY", "6HY", "6V9"},
  /* MacBook5,1     */ {"1AQ", "6J9", "6J8", "6J0", "6J7", "6JM", "6JC", "6JB", "6JA", "6JD", "7WU", "7WV", "7WY", "7WZ", "6ET", "6EU", "6ER", "6EG", "1AX", "8RE", "8RA", "8RC", "1B0", "1B5", "51N", "74F", "74G", "74J", "8AH", "8AD", "8AF", "8AG", "8Q6", "85Q", "85M", "85J", "8T6", "8T4", "8T2", "8T1", "8T0", "8S2", "8S3", "8S1", "8S4", "8S5", "8SR", "8SS", "8SP", "8SQ", "8SV", "8SW", "8ST", "8SU", "8SZ", "8SX", "8SY", "8SN", "8SL", "8SM", "8A3", "8RM", "8RL", "8RD", "8RB", "8RT", "8RQ", "8RP", "56H", "56J", "56K", "56G", "80D", "804", "8QS", "8QR", "8QT", "8QU", "6EH", "6VE", "6KJ"},
  /* MacBook5,2     */ {"9GU", "8CP", "79F", "79E", "79D", "85D", "7A2", "88J", "8SJ", "4R1", "4R3", "4R2", "93K", "9GV"},
  /* MacBook6,1     */ {"GAY", "8PX", "8PW"},
  /* MacBook7,1     */ {"F5X"},
  /* MacBook8,1     */ {"GCN3", "FFVW", "FFVY", "FG46", "FGC4", "FGMR", "FGMT", "FL8N", "FM8L", "FM8M", "FM8N", "FMLG", "FP12", "GCN1", "GCN2", "GCN4", "GKK3", "GKK2", "GKJQ", "GKJR", "GL69", "GL6C", "GL6G", "GL6F", "GL6D", "GL6H", "GR88", "GF85", "GR8C", "GR8G", "GR8F", "GR8D", "GR89", "GF84", "GF83", "GF82", "GKK5", "GKK4", "FWW4", "FWW5", "FWW6", "FWW3"},
  /* MacBook9,1     */ {"HDNK", "GTHR", "GTHT", "GTHV", "GTHW", "GTHX", "GTHY", "GTJ0", "GTJ1", "GTJ2", "GTJ3", "GTJ4", "GTJ6", "GTJ7", "GTJ8", "GTJ9", "GTJC", "GTJD", "H3QW", "H3QX", "H3QY", "H3R5", "H3R6", "H3R7", "HD8M", "GTGW", "JC5J", "HRMD", "HRMG", "HRMF"},
  /* MacBookAir1,1  */ {"18X", "1AE", "14J", "141", "12G", "13Q", "6T6", "6T5", "5YW", "5YV"},
  /* MacBookAir2,1  */ {"9A7", "9A8", "9A5", "9A6"},
  /* MacBookAir3,1  */ {"D0QX", "DDQW"},
  /* MacBookAir3,2  */ {"DDR3", "DDR1"},
  /* MacBookAir4,1  */ {"DJY8", "DJY9", "DJYC", "DJYD", "DRHF", "DRKH", "DTJW", "DTJY", "DTK1", "DTK2", "DW1C", "DW4J", "DWWM", "DWWN", "DY2M", "F2JP"},
  /* MacBookAir4,2  */ {"DJWT", "DJWQ", "DJWR", "DJWV", "DRKG", "DRQ4", "DTJT", "DTJV", "DTK0", "DW1N", "DW4H", "F14R", "F14V", "F2JQ", "F75Y"},
  /* MacBookAir5,1  */ {"DRV6", "DRV7", "DRV8", "DRV9", "F569", "F56C", "F56G", "F57H", "F5MV", "F67D", "F67F", "F67K", "F67L", "F67M", "F88G", "F88K", "F88V", "F910"},
  /* MacBookAir5,2  */ {"DRVC", "DRVD", "DRVF", "DRVG", "F2FV", "F56D", "F56F", "F56H", "F56J", "F57J", "F5MW", "F67G", "F67H", "F67J", "F67P", "F6TN", "F760", "F90Y"},
  /* MacBookAir6,1  */ {"F5NT", "F5N7", "F5N8", "F5YV", "F5YW", "FH51", "FH52", "FKYN", "FKYP", "FLCF", "FMR5", "FMR6", "FMR9", "FMRC", "FMRD", "FMRF", "FMRG", "FMRM", "FMRN", "FN5M", "FN7F", "FP2N", "FP3C", "FQLG", "FT30", "FM72", "G083", "G084", "G2CF", "G2GH", "G2GJ", "G2PY", "G2Q0", "G4FY", "G4H0", "G4H4", "G4HK", "G4HM", "G58J", "G5RK", "G5RL", "G5RM", "G6D3", "GP4N", "GP4P", "GLK9"},
  /* MacBookAir6,2  */ {"F5V7", "F5V8", "F6T5", "F6T6", "FH53", "FKYQ", "FKYR", "FLCG", "FM23", "FM3Y", "FM74", "FMR7", "FMR8", "FMRH", "FMRJ", "FMRK", "FMRL", "FMRV", "FMRW", "FMRY", "FN3Y", "FN40", "FN7G", "FP2P", "FQL9", "FQLC", "FQLD", "FQLF", "G6PM", "G085", "G086", "G2CC", "G2CD", "G2GK", "G2GL", "G2GM", "G2GN", "G356", "G4H1", "G4H2", "G4H3", "G4HN", "G4HP", "G58K", "G5RN", "G5RP", "G5RQ", "G6D4", "G6D5", "G829", "G8J1", "GP4L", "GP4M", "GLK7", "GLK8"},
  /* MacBookAir7,1  */ {"GFWK", "GFWL", "GFWM", "GFWN", "GFWP", "GKJY", "GKK0", "GL28", "GL2D", "GL2F", "GL2H", "GLCQ", "GMC5", "GMC6", "GMC7", "GMC8", "GMC9", "GNJK", "GNJL", "GNJG", "HYVM", "GL27", "J762", "GL29", "GL26", "GL2C"},
  /* MacBookAir7,2  */ {"G940", "G941", "G942", "G943", "G944", "GKJT", "GKJV", "GLCN", "GLCP", "GM14", "GM15", "GM38", "GM9G", "GMC3", "GN8C", "GNJJ", "H3QD", "H3QF", "H3QJ", "H3QK", "H569", "HD80", "GM6M", "J6VL", "GNKM", "H8VV", "H8VW", "H8VT", "H8VX", "HF4H", "HF4F", "HF9N", "GMD3", "HDV6", "HDV4", "HDV5", "HD7X", "GL25", "GL24", "GL23", "GL22", "GL21", "GL20", "HD98", "J8XH", "J8XG", "JCD6", "J9TN", "J9TQ", "J9TP", "MFWJ", "LQF1", "LQ07", "J8N7", "JC9H", "J9HX", "JFLY", "JKHD", "JKHF", "J1WK", "J1WL", "J1WM", "J1WV", "J1WT"},
  /* MacBookAir8,1  */ {"JK78", "JK77", "JK7C", "JK7D", "JK7F", "JK7G", "JK7L", "JK7M", "JK7P", "JK7Q", "JK7R", "JK7T", "LQDD", "LR0X", "LLDP", "LR0Y", "LLDQ", "LLDN", "MCKR", "MCKT", "LK88", "LK87", "LK86", "MCKP", "MCKQ", "LQDC"},
  /* MacBookAir8,2  */ {"LYWM", "M6X5", "LYWG", "LYWT", "LYWV", "LYWP", "LYWQ", "LYWR", "M6X7", "LYWL", "LYWN", "LYWH", "LYWJ", "LYWK"},
  /* MacBookPro1,1  */ {"VJ1"},
  /* MacBookPro1,2  */ {"THY"},
  /* MacBookPro10,1 */ {"DKQ1", "DKQ2", "DKQ4", "DKQ5", "F51R", "F5Y2", "F69W", "F69Y", "F6DN", "F6F3", "F6L9", "F8JY", "F96W", "F9F1", "F9F2", "FCQ3", "FMLK", "FFT0", "FFT1", "FFT2", "FFT3", "FFT4", "FG1H", "FG1J", "FGFH", "FGFJ", "FGFK", "FGFL", "FGN7", "FGWF", "FGWG", "FGWH", "FHCQ", "FHCR", "FJ47", "FJVJ", "FL94", "FR8D"},
  /* MacBookPro10,2 */ {"DR53", "DR54", "DR55", "DR56", "F775", "F776", "F7YF", "F897", "F8V6", "F8V7", "F8V8", "F9JT", "F9V1", "F9VQ", "FG7Q", "FG7R", "FL85", "FMLJ", "FFRP", "FFRR", "FG1F", "FG28", "FGM8", "FGN5", "FGN6", "FGPJ", "FHCH", "FHN0"},
  /* MacBookPro11,1 */ {"FH00", "FGYY", "FH01", "FH02", "FH03", "FH04", "FH05", "FRF6", "FRF7", "FRQF", "FT4Q", "FT4R", "FT4T", "FT4V", "FTC9", "FTCD", "FTCH", "FTCK", "FTCL", "FTPH", "FTPJ", "FTPK", "FTT4", "FVVW", "FVWQ", "G3QJ", "G3QK", "G4N6", "G4N7", "G3QH", "G3QQ", "G3QR", "GDJM", "G8L0", "G971", "G970", "G972", "G96R", "G96V", "G96W", "G96T", "G96Y", "G7YQ", "G7YR", "G3QL", "G3QT", "G7RD", "G7RF", "G9FN", "G9FL", "G9FM", "G9FR", "G9FP", "G9FQ", "FWKF"},
  /* MacBookPro11,2 */ {"G86R", "FD56", "G3QC", "G3QG", "G3QN", "G8J7", "G8F4", "G8L1", "G974", "G9L8", "G9L9", "G9L7", "G96P", "G96Q", "G96K", "G96N", "G96L", "G96M", "G973", "G9L6", "GDPP", "G9JN", "G86Q", "G86P", "G9FT"},
  /* MacBookPro11,3 */ {"FR1M", "FD57", "FD59", "G3QP", "FTPY", "G5HL", "G4JQ", "FVN4", "FWKK", "FWKL", "FRG3", "FRG2", "FVYN", "FTTJ", "FRDM", "FTK1", "FTK0", "FTPN", "FTPL", "FTPM", "FTPR", "FTPP", "FTPQ", "FTPV", "FTPW", "FTPT", "FRQL", "FRQK", "FRQJ", "FRQH", "FT4P", "FD58", "FWFY", "FWHW"},
  /* MacBookPro11,4 */ {"G8WN", "G8WL"},
  /* MacBookPro11,5 */ {"G85Y", "G3QD", "G8WM", "G8WP", "G8WQ", "GQCT"},
  /* MacBookPro12,1 */ {"H1DP", "FVH3", "FVH4", "FVH5", "FVH6", "FVH7", "FVH8", "FVH9", "GKJG", "GKJM", "GKJN", "GL36", "GL37", "GM0V", "GM0W", "GM10", "GM11", "GM12", "GM13", "GQR4", "GQR5", "GQR6", "H1DQ", "GN24", "HV59", "GL34", "GL35", "J69C", "GM0Y", "HTYF", "GMDF", "H1WK", "J4NY"},
  /* MacBookPro13,1 */ {"GVC1", "GVC8", "GY25", "GY6N", "HV5M", "HV5H", "HV5J", "HV5K", "HV5L", "HV5G", "HV5D", "HV5N", "HWCH", "HYP5", "J21W", "J5KW"},
  /* MacBookPro13,2 */ {"GYFH", "GTDX", "GTFJ", "GYGR", "HF1R", "HF1P", "HF1Q", "HF1T", "HP49", "HP4D", "HWH2", "HXD5", "GTFK"},
  /* MacBookPro13,3 */ {"GTFN", "GTDY", "GTF1", "GTFL", "GTFM", "H03M", "H03Q", "H03T", "H03Y", "H040", "HXF8", "HWCG", "HXD3"},
  /* MacBookPro14,1 */ {"HV29", "HV22", "HV2F", "HV2J", "JJ3D", "J8F0", "J8F1", "J8F2", "JKXH", "JCPR", "J9JY", "J9JX", "J9JQ", "J9JP", "J9JR", "J9JT", "J9JW", "J9JV", "J9JM", "J9JN", "J9K8", "J9K9", "J9K6", "J9K7", "J9K4", "J9K5", "J9K2", "J9K3", "J9K0", "J9K1", "J9KC", "HV2H", "HV2D", "HV2G", "HV27", "JD9D", "J8DY"},
  /* MacBookPro14,2 */ {"HV2N", "HV2M", "HV2R", "JJ3H", "JJ3J", "JJ3G", "JJ3F", "JKXM", "JHTF", "K141", "J9JH", "J9JD", "J9JG", "J9JF", "J9J9", "J9J8", "J9J1", "J9J3", "J9J2", "J9J5", "J9J4", "J9J7", "J9J6", "JCYQ", "HV2L", "HV2X", "HV2T", "HV2V", "HV2W", "HV2P", "HV2Q"},
  /* MacBookPro14,3 */ {"HTD5", "HTD6", "HTD8", "HTD9", "HTDF", "HTDH", "HTDD", "JD06", "JD04", "JHTD", "J6CQ", "J6CP", "J939", "J925", "J926", "HTDC", "J8KC", "J93P", "J93F", "J93G", "J93D", "J93C", "J93N", "J93L", "J93M", "J93J", "J93K", "J93H", "J936", "J937", "J934", "J935", "J932", "J933", "J931", "J938", "HTD7", "HTDG"},
  /* MacBookPro15,1 */ {"KGYG", "JG5H", "JG5J", "JG5K", "JG5L", "JG5M", "JGH5", "JGH6", "JGH7", "JGH8", "KGYF", "KGYH", "KQ9Q", "KQ9R", "KQ9T", "KQ9V", "KQ9W", "KQ9X", "KQ9Y", "KQC0", "KQC1", "KQC2", "KQC3", "KQC4", "KQC5", "KQC6", "KQC7", "KQC8", "KQC9", "KQCC", "KQCD", "KQCF", "KQCG", "KQCH", "KQCJ", "KQCK", "KQCL", "KQCM", "KQCN", "KQCP", "KQCR", "KQCT", "KQCV", "KQCW", "KQCX", "KWJ2", "LCM6", "MJLT", "L4HW", "KQCQ", "LC8K", "LC8J", "LC8L", "L539", "L53D", "L4HX", "L7GC", "MJLR"},
  /* MacBookPro15,2 */ {"JHCC", "JHC8", "JHC9", "JHCD", "JHCF", "JHD2", "JHD3", "JHD4", "JHD5", "KK98", "KK99", "KK9C", "KQ1X", "KQ1Y", "KQ20", "KQ21", "KQ22", "KQ23", "KQ24", "KQ25", "KQ26", "KQ27", "LVDC", "LVDM", "L42X", "L4FF", "L4FG", "L4FD", "L4FC", "L4FJ", "L4JT", "LK8C", "L7GD"},
  /* MacBookPro15,3 */ {"LVCG", "LVCJ", "LVDQ", "LVDR", "LVDV", "LVDT", "MVC0", "LVCL", "LVCF", "LVCK", "LVCH", "MV9T"},
  /* MacBookPro15,4 */ {"L40Y", "L410", "L411", "L412", "L413", "L414", "L415", "L416"},
  /* MacBookPro2,1  */ {"W0H"},
  /* MacBookPro2,2  */ {"W0L"},
  /* MacBookPro3,1  */ {"X91"},
  /* MacBookPro4,1  */ {"YP4", "27N", "48T", "4R5", "4R6", "1AJ", "2CE", "3LY", "3LZ", "2B0", "33B", "2DT", "2DX", "1JZ", "2PK", "1K0", "2MF", "1EK", "1EM", "1XR", "1XW", "1SH", "2AZ"},
  /* MacBookPro5,1  */ {"1G0", "6J2", "6J1", "6J5", "6J4", "6JW", "6JJ", "76Z", "8CR", "63X", "7XP", "7XL", "7XM", "7XN", "7X0", "4RA", "4RB", "6EJ", "6EK", "8Q3", "852", "5HX", "6GN", "6GP", "5TZ", "5TY", "8TW", "8TV", "8TQ", "8TZ", "8TY", "8TX", "973", "972", "971", "970", "6ZB", "8S6", "8S7", "8Q1", "8Q2", "8Q5", "6HZ", "4R9", "93G", "1GN", "1GK", "1GA", "71C", "71A"},
  /* MacBookPro5,2  */ {"2QP", "8YA", "8YB", "91T", "7XQ", "7XR", "7XS", "87N", "87L", "87M", "87K", "77A", "776", "7AS", "7AP", "2QT", "8G0", "8FK", "8FM", "8FL", "8FY", "8FZ"},
  /* MacBookPro5,3  */ {"7XK", "64C", "64B", "642", "644"},
  /* MacBookPro5,4  */ {"7XJ"},
  /* MacBookPro5,5  */ {"66D", "66E", "66J", "66H"},
  /* MacBookPro6,1  */ {"DC79"},
  /* MacBookPro6,2  */ {"AGW", "5W7"},
  /* MacBookPro7,1  */ {"ATM", "ATP"},
  /* MacBookPro8,1  */ {"DH2G", "DH2L", "DV13", "DH2H", "F299", "F298"},
  /* MacBookPro8,2  */ {"DF8X", "DRJD", "DRJF", "DF8V", "DRJC", "F0K6", "F0V2"},
  /* MacBookPro8,3  */ {"DF93", "DW48", "DMGH", "F140", "F13Y"},
  /* MacBookPro9,1  */ {"F1G4", "F1G3", "DV33", "F97M", "F7F5", "F9K9", "FL98", "FM89", "F762", "F761", "F686", "F687", "F38T", "F38R", "FT14", "F7F6", "FHP7", "F24T", "F5Y5", "F5Y6", "F5Y7", "F5Y8", "F5Y9", "F5YC", "F5YD", "F5YF", "F5YG", "F5YH", "F5YJ", "F5YK", "F5YL", "F5YM", "F5YN", "F5YP", "F8G9", "F8G8", "FLNH", "FLNJ", "FLNK", "FCQT", "F2J5", "F2J4"},
  /* MacBookPro9,2  */ {"DTY3", "DV30", "F5WW", "G3FY", "GDJL", "G05T", "G354", "H1DK", "GDL2", "G584", "GF65", "H1DN", "F973", "F4JL", "F4J2", "F447", "F8D5", "F5WV", "F68C", "F68D", "F7C1", "FCMM", "FYGF", "FYGD", "FYGC", "FYG9", "FWL4", "F6VG", "F5Y1", "F5Y3", "F5Y4", "F6LH", "F6LJ", "F9Q0"},
  /* MacPro1,1      */ {"UQ2", "0N2", "08S", "1MK", "0L6", "0L5", "0L3", "0L1", "0L0", "0L8", "0LU", "0LT", "0LS", "0LE", "0LD", "0LC", "0LB", "0LA", "0LN", "0LM", "0LL", "0L7", "0L2", "0L9", "0LP", "0KV", "0KW", "0KT", "0KU", "0KZ", "0KX", "0KY", "0L4", "0LH", "0VG", "0HA", "0GN", "0GP", "0Q0", "0PY", "0PX", "0PZ", "09H", "09G"},
  /* MacPro2,1      */ {"UPZ"},
  /* MacPro3,1      */ {"5J4", "XYK", "XYL", "1Z9", "27K", "1M3", "4R4", "329", "1BJ", "2BS", "14L", "2EE", "7AQ", "2DW", "31F", "31E", "5JA", "5JB", "5U8", "200", "2MB", "16U", "12K", "1L1", "1LY", "1LS", "1GP", "1ZA"},
  /* MacPro4,1      */ {"20H", "BXD", "7BF", "4PD", "4PC", "8TU", "8TR", "20G", "9MC", "9MD", "9MG", "9MK", "9MJ", "9ML", "8XG", "8XL", "8MC", "9QK", "8Q0", "9EU", "9EV", "8PZ", "93H"},
  /* MacPro5,1      */ {"EUH", "GWR", "HFC", "HFA", "HFD", "HFF", "HFG", "HFJ", "HFK", "HFL", "HFN", "EUF", "F4MG", "F4MH", "F501", "F4MJ", "F4MF", "F64C", "F64F", "F500", "F4YY", "F6TD", "F6TF", "F6TG", "F6TC", "F6T9", "F4MC", "F4MD", "F64D", "F648", "F649"},
  /* MacPro6,1      */ {"F9VM", "F693", "F694", "F9VN", "FRDW", "FRDY", "FRF0", "FRF1", "FRF2", "FRF3", "FRF4", "FRF5", "FRQC", "FT3F", "FT3G", "FT3H", "FT95", "FT96", "FT97", "FT98", "FT99", "FT9C", "FT9D", "FY3Y", "FY40", "G1LJ", "G1LK", "G1LL", "G1LM", "G1LN", "G1LP", "G1LQ", "G1LR", "G1LT", "G1LV", "G1LW", "G1LY", "G1M0", "G1M1", "G8GC", "G8GD", "J3RY", "J3RW"},
  /* MacPro7,1      */ {"0000"},
  /* Macmini1,1     */ {"U35"},
  /* Macmini2,1     */ {"YL2", "4NP"},
  /* Macmini3,1     */ {"19X", "19Y", "1BU", "1BV", "8NC", "9RR", "9RS", "92G", "9G7", "9G6", "9G5", "9G8", "306", "307"},
  /* Macmini4,1     */ {"DD6H"},
  /* Macmini5,1     */ {"DJD0", "DJD1", "DJD2", "DJD3", "DRHT", "DTCJ", "DTCK", "DTCM", "DW33", "DW34", "DW35", "DW36", "DW37", "DW38", "DW3C", "DYQJ"},
  /* Macmini5,2     */ {"DJD1", "DJD0", "DJD2", "DJD3", "DRHT", "DTCJ", "DTCK", "DTCM", "DW33", "DW34", "DW35", "DW36", "DW37", "DW38", "DW3C", "DYQJ"},
  /* Macmini5,3     */ {"DKDJ", "DJY7", "DRHR", "DTCL", "DTCT", "DTCV", "DW39", "DW3D"},
  /* Macmini6,1     */ {"DY3H", "DWYL", "DWYM", "DY3G", "F9RK", "F9RL", "F9RM", "F9VV", "F9VW", "F9W0", "F9W1", "F9W2", "FD9G", "FD9H", "FD9J", "FD9K", "FDWK", "FGML", "FRFP", "FW56", "FW57", "G430"},
  /* Macmini6,2     */ {"DWYN", "DY3J", "F9VY", "F9W3", "FC08", "FCCW", "FP14", "FP39"},
  /* Macmini7,1     */ {"G1J0", "G1HV", "G1HW", "G1HY", "G1J1", "G1J2", "GCVG", "GCVH", "GCVJ", "GCVN", "GCVP", "GCVQ", "GCVV", "GCVW", "GCVY", "GCW0", "GCW1", "GF1N", "GF1Q", "GF1T", "GJDC", "GHRN", "GNL0", "GN02", "H84M", "L7FY", "L9TM", "L9TN", "L9TP", "HCL5"},
  /* Macmini8,1     */ {"JYVX", "JYVW", "JYVY", "JYW0", "L960", "MCD6", "M7FV", "M7FT", "M99Q", "M99P", "MJHL", "MHGQ", "LVVM", "LVVN", "MKTR", "LVVL", "LVVJ", "LVVK", "LHPC", "M99N", "L95X", "L95Y"},
  /* Xserve1,1      */ {"V2Q", "00W"},
  /* Xserve2,1      */ {"X8S", "27P", "5WE", "5WD", "1H4", "3GM", "3GN", "31G", "20A", "32A", "1DR", "25N", "12E", "6EM", "24B", "1ZZ"},
  /* Xserve3,1      */ {"6HS", "8DE", "9N0", "9VJ", "9WM", "9ZP", "9ZQ", "9ZL", "8M3", "10J", "10S", "9SS", "9ST"},
  /* iMac10,1       */ {"5PE", "5PK", "5PC"},
  /* iMac11,1       */ {"5PJ", "5RU", "5PM"},
  /* iMac11,2       */ {"DB7"},
  /* iMac11,3       */ {"DNR", "DB6"},
  /* iMac12,1       */ {"DHJF", "F611"},
  /* iMac12,2       */ {"DHJQ", "DHJP", "DHJW", "FHCV", "F610"},
  /* iMac13,1       */ {"DNCT", "DNCR", "DNML", "DNMM", "F8QM", "F8QN", "F9RN", "FC6M", "FC6N", "FC6P", "FD55", "FD5Y", "FF7L"},
  /* iMac13,2       */ {"DNCW", "DNCV", "DNMN", "DNMP", "F29N", "F8QP", "F8QQ", "FD5T", "FD5V", "FFM8", "FFM9", "FFMC", "FFMD", "FFMF", "FFMG", "FFMJ", "FFMK", "FFML", "FFMM", "FFMN", "FFW0", "FFW1", "FG47", "FGMW", "FGMY", "FGRP", "FL8M", "FM8P", "FM8Q", "FMLH", "FP13", "FP62", "FTQ5", "FTQ4"},
  /* iMac13,3       */ {"FFYW", "FFYV", "FGPL", "FGPM", "FJQQ", "FLMH"},
  /* iMac14,1       */ {"F8J2", "F8J7", "FPF1", "FQMV"},
  /* iMac14,2       */ {"F8JC", "F8J4", "F8J5", "F8J9", "FLHH", "FPDY", "FPF0", "FPF3", "FPF4", "FQPG", "FQPH", "FQPJ", "FQPK", "FQPL", "FQPM", "FQPN", "FQPP", "FR20", "FR22", "FR2W", "FRM9", "FT4N", "FWQ5", "FWQ6", "FWQ7", "FWQ8", "FY15", "FY9D", "FY9F", "G6DP", "GHFF", "GQCX", "GRTV", "GW0V", "GW0W", "FR1W", "FR1Y"},
  /* iMac14,3       */ {"F8J3", "F8J8", "FPDW"},
  /* iMac14,4       */ {"FY0T", "FY0V", "FY65", "FY69", "G56J", "G56K", "G5W4", "G5W5", "G5W6", "G8L2"},
  /* iMac15,1       */ {"FY10", "FY11", "FY14", "FY68", "FY6F", "GCTM", "GDQY", "GDR3", "GDR4", "GDR5", "GDR6", "GDR7", "GDR8", "GDR9", "GDRC", "GFFQ", "GJDM", "GJDN", "GJDP", "GJDQ", "FY13", "FY6D", "GL1Q", "GL1R", "GL1T", "GL1V", "GL1W", "GV7V", "GPJN", "H682", "H5DN", "FY67"},
  /* iMac16,1       */ {"GF1J"},
  /* iMac16,2       */ {"GG7G", "GG78", "GG7F", "GG7H", "H0P7", "H1F3", "H1F5", "H1F7", "H1F8", "H1F9", "H25N", "H8L0", "H8L1", "H8L2", "H8L3", "H15R", "H28H", "H8KY", "GG7C", "H0KF", "H3RJ", "HLWV", "H1WR", "HYGQ", "HQ9W", "H2KW", "HHMG", "GF1L", "GF1M", "GF1K", "H0N6", "H1DX", "J0DJ", "J0DH", "J0DG", "H8KX", "GG77", "GG79", "GG7D", "H0P6", "H1DY", "HQ9V", "HQ9T", "H1F2", "H1F1", "H25M"},
  /* iMac17,1       */ {"GG7L", "GG7J", "GG7N", "GG7R", "GG7T", "GG7V", "GG80", "GG81", "GG82", "GQ17", "GQ18", "H0Q3", "H0Q4", "H0Q5", "H3GP", "H3GQ", "H3GR", "H3GT", "H3GV", "H3GW", "H8L5", "H8L6", "H3H4", "H3HJ", "HJRN", "H1H9", "H4JM", "H2YQ", "J0DK", "GG7Q", "HN8P", "H3H9", "H3H8", "H3H7", "H3H6", "H3H5", "H3H3", "H3H2", "H3H1", "H3H0", "H3HH", "H3HD", "H3HC", "HMMQ", "H3HG", "H3HF", "H3GX", "H3GY", "H3GN"},
  /* iMac18,1       */ {"H7JY", "H7VF", "JGDR", "MCD9", "MCD7", "KQFL", "MCD8", "H7K0", "H7VG", "JFRR"},
  /* iMac18,2       */ {"J1G5", "J9X5", "J9X4", "LQHG", "JGDT", "J1GC", "J1GF", "J1GD", "J1G8", "J1G9", "J1G6", "J1G7", "J608", "JKF9", "JFPW", "L7H6", "JP10"},
  /* iMac18,3       */ {"J1GJ", "J1GQ", "J1GG", "J9XC", "J9X7", "J9X6", "J9X9", "JNGD", "JNGF", "JCCR", "JCCT", "JT72", "J9X8", "JM3R", "JM3V", "J1GR", "J1GP", "J1GV", "J1GT", "J1GK", "J1GH", "J1GN", "J1GL", "J1GM", "JCND", "JC5L", "JX8H", "J2GJ", "J609", "J60C"},
  /* iMac19,1       */ {"JV3Q", "JV3P", "JV40", "JV41", "JV42", "JV43", "MC9K", "MC9J", "MX7W", "JV3N", "JV3T", "JV3W", "JV3R", "JV3Y", "JV3X", "MW2R", "MW2P", "MW2Q", "MW2V", "MW2W", "MW2T", "MQQP"},
  /* iMac19,2       */ {"JWDW", "JWDX", "MQ87", "MC9M", "MC9L", "MRVM", "MPM0", "MW28", "JWDY", "MMTK", "MMTL", "MTML", "MCC1", "JWF3", "JWF2", "JWF1", "JWF0", "JWF4"},
  /* iMac4,1        */ {"U2P"},
  /* iMac4,2        */ {"V2H"},
  /* iMac5,1        */ {"X1A"},
  /* iMac5,2        */ {"WH5"},
  /* iMac6,1        */ {"VGN"},
  /* iMac7,1        */ {"X87"},
  /* iMac8,1        */ {"2E2"},
  /* iMac9,1        */ {"6MJ", "6X0", "0TH", "9LN", "8TT", "8TS", "0TF", "8M5", "9EX", "9TH", "6MH", "6X3", "6X1", "6X2", "9F3", "0TM", "0TJ", "0TG", "9LR", "9LS", "9LP", "9LQ", "8XH", "0TL", "8M6", "259", "250", "9ET"},
  /* iMacPro1,1     */ {"HX87", "HX8F", "JL53", "JL54", "JL55", "JLCN", "JLCP", "JLCR", "JLCT", "JLCV", "JLCW", "JLCX", "JLCY", "JLD0", "JLD1", "JLD2", "MC9H", "M0XV"},
};

#define APPLE_BOARD_CODE_MAX 128
static const char *AppleBoardCode[][APPLE_BOARD_CODE_MAX] = {
  /* MacBook1,1     */ {"V3G", "VZ0", "TYU", "VZ1", "VMC", "VZ2", "WXS", "WXW", "X0W", "X10", "WXR", "WXV", "X0V", "X0Y", "WXT", "WXU", "X0X", "X0Z"},
  /* MacBook10,1    */ {"HJ9L", "HJ9M", "HJ9N", "HJ9P", "HJ9W", "HJ9X", "HJ9Y", "HJC0", "HJC5", "HJC6", "HJC7", "HJC8", "HJ9G", "HJ9H", "HJ9J", "HJ9K", "HJ9Q", "HJ9R", "HJ9T", "HJ9V", "HJC1", "HJC2", "HJC3", "HJC4", "HJCL", "HJCM", "HJCN", "HJCP", "HJD5", "HJD6", "HJD7", "HJD8", "HJDQ", "HJDR", "HJDT", "HJDV", "HJCQ", "HJCR", "HJCT", "HJCV", "HJD9", "HJDC", "HJDD", "HJDF", "HJDW", "HJDX", "HJDY", "HJF0", "HJC9", "HJCC", "HJCD", "HJCF", "HJCW", "HJCX", "HJCY", "HJD0", "HJDG", "HJDH", "HJDJ", "HJDK", "HJCG", "HJCH", "HJCJ", "HJCK", "HJD1", "HJD2", "HJD3", "HJD4", "HJDL", "HJDM", "HJDN", "HJDP", "HJF9", "HJFC", "HJFD", "HJFF", "HJFW", "HJFX", "HJFY", "HJG0", "HJGG", "HJGH", "HJGJ", "HJGK", "HJFG", "HJFH", "HJFJ", "HJFK", "HJG1", "HJG2", "HJG3", "HJG4", "HJGL", "HJGM", "HJGN", "HJGP", "HJF1", "HJF2", "HJF3", "HJF4", "HJFL", "HJFM", "HJFN", "HJFP", "HJG5", "HJG6", "HJG7", "HJG8", "HJF5", "HJF6", "HJF7", "HJF8", "HJFQ", "HJFR", "HJFT", "HJFV", "HJG9", "HJGC", "HJGD", "HJGF"},
  /* MacBook2,1     */ {"WES", "WEV", "W6V", "WET", "WEU", "WEW"},
  /* MacBook3,1     */ {""},
  /* MacBook4,1     */ {""},
  /* MacBook5,1     */ {""},
  /* MacBook5,2     */ {""},
  /* MacBook6,1     */ {""},
  /* MacBook7,1     */ {""},
  /* MacBook8,1     */ {"FV36", "FV3T", "FV5W", "FV9F", "FV6W", "FVC7", "FVF6", "FV87", "FV5H", "FVF0", "FV7P", "FVC8"},
  /* MacBook9,1     */ {"FV48", "FV8P", "FV9C", "FV9Q", "H6LL", "H6LM", "H6LN", "H6LP", "FV3K", "FV5M", "FV67", "FV77", "H6LQ", "H6LR", "H6LT", "H6LV", "FV3D", "FV4C", "FV9K", "FVC6", "H6M1", "H6M2", "H6M3", "H6M4", "FV89", "FV8Q", "FV8T", "FVCP", "H6M5", "H6M6", "H6M7", "H6M8"},
  /* MacBookAir1,1  */ {""},
  /* MacBookAir2,1  */ {""},
  /* MacBookAir3,1  */ {"DF83", "DF8D", "DF8G", "DF8L", "DG4L", "DG4M", "DF86", "DF8F", "DF8H", "DF8M", "DG4H", "DG4K", "DD0T", "DD14", "DD15", "DG4G", "DG4Q", "DD0Q", "DD0R", "DD0V", "DD12", "DG4T", "DG4V"},
  /* MacBookAir3,2  */ {"DCWQ", "DCX3", "DCXM", "DCXW", "DG4W", "DG4Y", "DCX7", "DCXP", "DCXQ", "DCXV", "DCWT", "DCWW", "DCX5", "DCXJ", "DG51", "DG52", "DCWV", "DCWX", "DCX4", "DCXF"},
  /* MacBookAir4,1  */ {"DK9L", "DLCP", "DLCT", "DY58", "DY5D", "DY5F", "DLCR", "DLD1", "DLD6", "DY59", "DY5C", "DY5G"},
  /* MacBookAir4,2  */ {"DP1G", "DP1J", "DP1P", "DY4Q", "DY4W", "DY4Y", "DP1H", "DP1K", "DP1L", "DY4J", "DY4M", "DY4R"},
  /* MacBookAir5,1  */ {"DYKF", "DYKK", "F27J", "F9DH", "DYKG", "F0V4", "F27D", "F9DK", "F27G", "F27H", "F27K", "F9DG", "F279", "F27C", "F27F", "F9DJ"},
  /* MacBookAir5,2  */ {"F25Q", "F25Y", "F27Y", "F9DF", "F25P", "F25T", "F27Q", "F9D8", "F25N", "F25R", "F27T", "F9D7", "F25V", "F25W", "F27R", "F9D9"},
  /* MacBookAir6,1  */ {"FD09", "FD0C", "FD08", "FD0D", "FY44", "FY47", "G3MT", "G8JP", "FY46", "FY48", "G3MY", "G8JM", "F6V4", "F9Q1", "G3MW", "G8JN", "F9Q2", "F9Q3", "G3MV", "G8JQ"},
  /* MacBookAir6,2  */ {"FD47", "FD49", "FD48", "FD4C", "FY58", "FY5C", "G3N3", "G8JR", "FY56", "FY57", "G3N4", "G8JV", "FHDQ", "FHDV", "G3N5", "G8JT", "FHDT", "FHDW", "G3N2", "G8JW"},
  /* MacBookAir7,1  */ {"G90F", "G90R", "G90V", "G909", "G90J", "G90K", "G90G", "G90M", "G90W", "G90Q", "G90Y", "G910"},
  /* MacBookAir7,2  */ {"G91Q", "G91T", "G91Y", "G925", "G928", "G92C", "G922", "G929", "G92F", "G91R", "G926", "G92G"},
  /* MacBookAir8,1  */ {"KN2R", "KN7H", "KN7V", "KN86", "KN8M", "KN34", "KN3J", "KN3Y", "KMXD", "KMXQ", "KMY4", "KMYH", "KNDX", "KNF8", "KN9P", "KNC2", "KNCF", "KNCR", "KN5C", "KN5P", "KN62", "KN6F", "KN0L", "KN0Y", "KN19", "KN1N", "KNGC"},
  /* MacBookAir8,2  */ {"0000"},
  /* MacBookPro1,1  */ {""},
  /* MacBookPro1,2  */ {""},
  /* MacBookPro10,1 */ {"DY3V", "DY3W", "DY3Y", "DY40", "DY41", "DY42", "DY43", "DY44", "DY45", "DY4C", "F78Q", "F78Y", "F790", "DYJ5", "DYJ6", "DRDN", "DRDP", "DRDW", "DRF0", "DRF1", "DRF4", "DT9D", "DT9F", "DT9G", "DT9H", "F78N", "F78P", "DRDQ", "DRDT", "DYW4", "DYW5", "F0HM", "F0HN", "F0HR", "F0HT", "F0HV", "F0HY", "F0J3", "F0JD", "F78T", "F791", "F0JC", "FF63", "FF65", "FF67", "FF6W", "FF70", "FF72", "FF74", "FF69", "FF6D", "FF6G", "FF6J", "FF6L", "FF6N", "FF6Q", "FF6T", "FFW6", "FFW7", "FFWG", "FFWJ", "FFWK", "FFWM", "FFWN", "FFWP", "FFW8", "FFW9", "FFWC", "FFWD", "FFWF", "FFWH", "FFWL", "FFWQ", "FF64", "FF66", "FF68", "FF6F", "FF6Y", "FF71", "FF73", "FF75", "FF6C", "FF6H", "FF6K", "FF6M", "FF6P", "FF6R", "FF6V", "FF7M"},
  /* MacBookPro10,2 */ {"F16P", "F16V", "F26L", "F2WV", "F16M", "F16N", "F26H", "F2WQ", "FF58", "FF5C", "FF5F", "FF5H", "FF59", "FF5D", "FF5G", "FF5J"},
  /* MacBookPro11,1 */ {"FH31", "FH35", "FJYK", "FJYL", "FJYM", "FJYR", "FJYY", "FK00", "FMQF", "FMQG", "FN3L", "FN3P", "FN3Q", "FLJJ", "FLJK", "FLJL", "FJYV", "FK01", "FN3K", "FN3M", "FN3N", "FJYT", "FJYW", "FK02", "G3LM", "G3LP", "G3LG", "G3LH", "G3LQ", "GC9Q", "G3LT", "G3M0", "G3LK", "G3LL", "G3LN", "GC9T", "G3LR", "G3LV", "G3LJ", "G3LW", "G3LY", "GC9R"},
  /* MacBookPro11,2 */ {"FJQW", "FJRP", "FJRR", "FJRH", "FJRJ", "FJRN", "FJRC", "FJRV", "FJTQ", "FJT1", "FJTH", "FJTL", "FJRY", "FJTC", "FJTP", "FJR7", "FJR9", "FJRM", "G3M6", "G3M8", "G3M9", "G3M4", "G3M5", "G3M7", "G3MG", "G3MJ", "G3MK"},
  /* MacBookPro11,3 */ {"FP52", "FP58", "FP5C", "FP50", "FP53", "FP54", "G3MH", "G3ML", "G3MM", "G3MG", "G3MJ", "G3MK"},
  /* MacBookPro11,4 */ {"GDQP", "GDQR", "GDQQ", "GDQT", "G7RP", "G7RQ"},
  /* MacBookPro11,5 */ {"GF2C", "GF2D", "GF2F", "GF2G", "GQDF", "GQDG", "GQDH", "GQDJ", "H4P0", "H4P1", "HLG2", "HLG3", "G9LM", "GC9P", "GCQR", "GCQT"},
  /* MacBookPro12,1 */ {"GDVV", "GDVQ", "GDVW", "GDW6", "GDVY", "GDVT", "GDW4", "GDW5", "GDVN", "GDVR", "GDVN", "GDVR", "GQ10", "GDW1", "GDW2", "GDW3"},
  /* MacBookPro13,1 */ {"HMHK", "HMHL", "HMHM", "HMHC", "HMHD", "HMHF", "HMHN", "HMHP", "HMHQ", "HMHG", "HMHH", "HMHJ"},
  /* MacBookPro13,2 */ {"H9W8", "H9WC", "H9WP", "H9WR", "H9W7", "H9W9", "H9WN", "H9WQ", "H1QG", "H1QJ", "H9WK", "H9WM", "H0D3", "H0D5", "H9WD", "H9WG", "H1QF", "H1QH", "H9WJ", "H9WL", "H0F2", "H0F5", "H9X4", "H9X6", "H0D9", "H0DD", "H9WV", "H9WX", "H0DX", "H0F0", "H9X0", "H9X2", "H0F1", "H0F4", "H9X3", "H9X5", "H0D8", "H0DC", "H9WT", "H9WW", "H0DV", "H0DY", "H9WY", "H9X1", "H0FD", "H0FG", "H9XK", "H9XM", "H5F6", "H5F8", "H9X8", "H9XC", "H0F7", "H0F9", "H9XF", "H9XH", "H0FC", "H0FF", "H9XJ", "H9XL", "H5F5", "H5F7", "H9X7", "H9X9", "H0F6", "H0F8", "H9XD", "H9XG"},
  /* MacBookPro13,3 */ {"HCF9", "HCFC", "HCFD", "HCFL", "HCFV", "HCGR", "H54Y", "HCF3", "HCF4", "HCF5", "HCFJ", "HCFN", "HCFQ", "H3PG", "H3PL", "HCFF", "HCFG", "HCFH", "HCFM", "HCFR", "HCFW", "HCFF", "HCFG", "HCFH", "HCFM", "HCFR", "HCFW", "HCDN", "HCDQ", "HCF6", "HCF7", "HCF8", "HCFK", "HCFP", "HCFT", "H551", "HCDK"},
  /* MacBookPro14,1 */ {"HWVP", "HWVR", "HWVV", "HWVN", "HWVQ", "HWVT", "JDDH", "JDDK", "JDDM", "HT4H", "HT4K", "HT4N", "HT4G", "HT4J", "HT4L"},
  /* MacBookPro14,2 */ {"HRPC", "HRPF", "HRPH", "HRR8", "HRRC", "HRRF", "HRNX", "HRP0", "HRP2", "HRQV", "HRQX", "HRR0", "HRP4", "HRP6", "HRP8", "HRR2", "HRR4", "HRR6", "HRP9", "HRPD", "HRPG", "HRR7", "HRR9", "HRRD", "HRNW", "HRNY", "HRP1", "HRQT", "HRQW", "HRQY", "HRP3", "HRP5", "HRP7", "HRR1", "HRR3", "HRR5", "HRQ0", "HRQ2", "HRQ4", "HRRX", "HRT0", "HRT2", "HRPK", "HRPM", "HRPP", "HRRH", "HRRK", "HRRM", "HRPR", "HRPV", "HRPX", "HRRP", "HRRR", "HRRV", "HRPY", "HRQ1", "HRQ3", "HRRW", "HRRY", "HRT1", "HRPJ", "HRPL", "HRPN", "HRRG", "HRRJ", "HRRL", "HRPQ", "HRPT", "HRPW", "HRRN", "HRRQ", "HRRT", "HRQM", "HRQP", "HRQR", "HRTK", "HRTM", "HRTP", "HRQ6", "HRQ8", "HRQC", "HRT4", "HRT6", "HRT8", "HRQF", "HRQH", "HRQK", "HRTC", "HRTF", "HRTH", "HRQL", "HRQN", "HRQQ", "HRTJ", "HRTL", "HRTN", "HRQ5", "HRQ7", "HRQ9", "HRT3", "HRT5", "HRT7", "HRQD", "HRQG", "HRQJ", "HRT9", "HRTD", "HRTG"},
  /* MacBookPro14,3 */ {"J1JH", "J1JJ", "J1JK", "J1JL", "J1JM", "J1JN", "J1JP", "J1JQ", "J1JR", "HRDM", "HRDR", "HRFF", "HRFK", "HRL5", "HRLK", "HYR3", "HYR7", "HYRW", "J1HH", "J1HJ", "J1HK", "J1HL", "J1HM", "J1HN", "J1HP", "J1HQ", "J1HR", "HRDK", "HRDP", "HRFC", "HRFH", "HRL3", "HRLH", "HYR1", "HYR5", "HYRT", "J1JT", "J1JV", "J1JW", "J1JX", "J1JY", "J1K0", "J1K1", "J1K2", "J1K3", "J1J5", "J1J6", "J1J7", "J1J8", "J1J9", "J1JC", "J1JD", "J1JF", "J1JG", "HRDL", "HRDQ", "HRFD", "HRFJ", "HRL4", "HRLJ", "HYR2", "HYR6", "HYRV"},
  /* MacBookPro15,1 */ {"JP4F"},
  /* MacBookPro15,2 */ {"JH4R", "JN1C", "JN1D", "JN1F", "JN1G", "JN1H", "JN1J", "JN1T", "JN1V", "JN1W", "JN1X", "JN1Y", "JN20", "JN21", "JN22", "JN23", "JN0X", "JN0Y", "JN10", "JN11", "JN12", "JN13", "JN1T", "JN1V", "JN1W", "JN1X", "JN1Y", "JN20", "JN21", "JN22", "JN23", "JN1K", "JN1L", "JN1M", "JN1N", "JN1Q", "JN1R", "JN2K", "JN2L", "JN2M", "JN14", "JN15", "JN16", "JN17", "JN18", "JN19", "JN24", "JN25", "JN26", "JN27", "JN28", "JN29", "JN2C", "JN2D", "JN2F", "JJ50", "JJ51", "JJ52", "JJ53", "JJ54", "JJ55", "JJ62", "JJ63", "JJ64", "JH4Q", "JH4T", "JH4W", "JH4Y", "JH50", "JJ5F", "JJ5G", "JJ5H", "JJ5J", "JJ5K", "JJ5L", "JJ5M", "JJ5N", "JJ5P", "JJ56", "JJ57", "JJ58", "JJ59", "JJ5C", "JJ5D", "JJ65", "JJ66", "JJ67", "JH51", "JH52", "JH53", "JH54", "JH55", "JH56", "JJ5Q", "JJ5R", "JJ5T", "JJ5V", "JJ5W", "JJ5X", "JJ5Y", "JJ60", "JJ61"},
  /* MacBookPro15,3 */ {"0000"},
  /* MacBookPro15,4 */ {"0000"},
  /* MacBookPro2,1  */ {""},
  /* MacBookPro2,2  */ {""},
  /* MacBookPro3,1  */ {""},
  /* MacBookPro4,1  */ {""},
  /* MacBookPro5,1  */ {""},
  /* MacBookPro5,2  */ {""},
  /* MacBookPro5,3  */ {""},
  /* MacBookPro5,4  */ {""},
  /* MacBookPro5,5  */ {""},
  /* MacBookPro6,1  */ {""},
  /* MacBookPro6,2  */ {""},
  /* MacBookPro7,1  */ {""},
  /* MacBookPro8,1  */ {"DM6D", "DM6F", "DM6J", "DM6K", "DM6L", "DM6N", "DM6P", "DM6T", "DMLK", "DMLM", "DMLP", "DMLR", "DRKQ", "DRKR", "DRKT", "DRLN", "DRMH", "DRMJ", "DTFL", "DTFM", "DTFN", "DTFQ", "DTFY", "DTG0", "DM6G", "DM6H", "DM6M", "DM6Q", "DM6R", "DM6V", "DM6W", "DMLL", "DMLN", "DMLQ", "DMLT", "DMLV", "DRKM", "DRKN", "DRKP", "DRKV", "DRMG", "DRMK", "DTFJ", "DTFK", "DTFR", "DTFT", "DTFV", "DTFW", "DTML", "DTMR", "DTMV", "DTMY", "DTN2", "DTN5", "DTMK", "DTMM", "DTMQ", "DTN0", "DTN3", "DTN4"},
  /* MacBookPro8,2  */ {"DMMN", "DMMQ", "DMMR", "DMMW", "DMN4", "DMN6", "DMNN", "DMNP", "DMNQ", "DMNR", "DMNT", "DMNV", "DRMN", "DRMY", "DRN0", "DRN2", "DRN4", "DRN6", "DRP8", "DRPM", "DRPT", "DRPW", "DRQ0", "DRQ3", "DTHH", "DTHR", "DTHW", "DTHY", "DTJ1", "DMML", "DMMM", "DMMV", "DMN1", "DMN3", "DMN5", "DMN7", "DMN8", "DMN9", "DMND", "DMNF", "DMNG", "DRMQ", "DRMT", "DRMV", "DRN1", "DRN7", "DRN8", "DRPC", "DRPK", "DRPL", "DRPQ", "DRPV", "DRQ2", "DTHJ", "DTHN", "DTHQ", "DTHT", "DTHV", "DMMK", "DMMP", "DMMT", "DMMY", "DMN0", "DMN2", "DMNC", "DMNH", "DMNJ", "DMNK", "DMNL", "DMNM", "DRMM", "DRMP", "DRMR", "DRMW", "DRN3", "DRN5", "DRP9", "DRPN", "DRPP", "DRPR", "DRPY", "DRQ1", "DTHK", "DTHL", "DTHM", "DTHP", "DTJ6", "DTWK", "DTWL", "DTWM", "DTWN", "DTWP", "DTWQ", "DTWR", "DTWT", "DTWV", "DTWW", "DTWY", "DTY0", "DYM2", "DYM3", "DYM4", "DYM5", "DYMC", "DYNC", "F16H", "DYN4", "DV36", "DV37", "DV3D", "DV3F", "DV3G", "DV3H", "DV3J", "DV3M", "DV3P", "DV3V", "DV3Y", "DV40", "DYM6", "DYM8", "DYM9", "DYMF", "DYMJ", "DV32", "DV34", "DV38", "DV39"},
  /* MacBookPro8,3  */ {"DM5K", "DM5L", "DM5N", "DM5Q", "DM5R", "DM5W", "DMM0", "DMM1", "DMM5", "DMM9", "DMMC", "DMMD", "DM5J", "DM5M", "DM5P", "DM5T", "DM5V", "DM5Y", "DMM2", "DMM3", "DMM4", "DMM6", "DMM7", "DMM8", "DTYV", "DTYW", "DV01", "DV02", "DV03", "DV06", "DV07", "DV0C", "DV0H", "DV0J", "DV0K", "DV0M", "DYL5", "DYL7", "DYLC", "DYLF", "DYLG", "DTYT", "DTYY", "DV00", "DV04", "DV05", "DV08", "DV09", "DV0D", "DV0F", "DV0G", "DV0L", "DV0N", "DYL4", "DYL6", "DYL8", "DYL9", "DYLD"},
  /* MacBookPro9,1  */ {"F327", "F32C", "F3JG", "F3JK", "F324", "F325", "F3JH", "F3JJ", "F328", "F329", "F3JF", "F3JL"},
  /* MacBookPro9,2  */ {"F1YJ", "F1YL", "F1YM", "F1YG", "F1YH", "F1YK"},
  /* MacPro1,1      */ {""},
  /* MacPro2,1      */ {""},
  /* MacPro3,1      */ {""},
  /* MacPro4,1      */ {""},
  /* MacPro5,1      */ {""},
  /* MacPro6,1      */ {"FHDD", "FNN1"},
  /* MacPro7,1      */ {"0000"},
  /* Macmini1,1     */ {""},
  /* Macmini2,1     */ {""},
  /* Macmini3,1     */ {""},
  /* Macmini4,1     */ {"DC2D", "DC40", "DC5G", "DC6Y"},
  /* Macmini5,1     */ {"DKP2"},
  /* Macmini5,2     */ {"DK22", "DN77"},
  /* Macmini5,3     */ {"DHDN"},
  /* Macmini6,1     */ {"F1HC", "DVF8"},
  /* Macmini6,2     */ {"DVF9", "F1H8", "F1G2", "F1H9"},
  /* Macmini7,1     */ {"G0MC", "FWY2", "FYRD", "G3N7", "G0MH", "G0MJ", "G3ND", "G0MK", "FYRF", "G0MF", "G3NC", "FYRK", "FYRH", "FYRJ", "G3N9", "G0MM", "G0MN", "G0MP", "G3N8"},
  /* Macmini8,1     */ {"KXPG", "KXVT", "KXW5", "KXQJ", "KXQW", "KXX7", "KXRY", "KXV3", "KXVG", "KXQ5", "KXYC", "KXWJ", "KXWW"},
  /* Xserve1,1      */ {"V1C"},
  /* Xserve2,1      */ {"OVE", "XZU"},
  /* Xserve3,1      */ {"63C", "1PH"},
  /* iMac10,1       */ {""},
  /* iMac11,1       */ {""},
  /* iMac11,2       */ {""},
  /* iMac11,3       */ {""},
  /* iMac12,1       */ {"DJWK", "DM66", "DNJK", "DP0H", "DKG1", "DM65", "DNJJ", "DKG2", "DM67", "DNJL", "DP0K", "DP00"},
  /* iMac12,2       */ {"DJWM", "DMT3", "DMT5", "DJWN", "DM69", "DJWP", "DM6C"},
  /* iMac13,1       */ {"DYWF", "F117", "F502", "F505", "F9GY", "F9H0", "F9H1", "F9H2", "FF4G", "FF4H", "FF4J", "FF4K", "FF4L"},
  /* iMac13,2       */ {"F2FR", "F653", "F49P", "F651", "F49R", "F652", "DYW3", "F64V", "F0V5", "F64W"},
  /* iMac13,3       */ {"F8GR"},
  /* iMac14,1       */ {"FM59"},
  /* iMac14,2       */ {"F8YL", "FCTC", "FC3F", "FC3J", "FN7H", "FN71", "FN72", "FN3W"},
  /* iMac14,3       */ {"F9RR", "F9T5", "F9RW", "F9T3"},
  /* iMac14,4       */ {"G36D", "G36G", "G3W2", "FT57", "FT5F", "G3W3"},
  /* iMac15,1       */ {"G2Y7", "G2Y8", "GG3L", "GG3N", "G2QD", "G2QF", "GG3T", "GG3W", "FT04", "FW6K", "GG3K", "GG3M", "FW29", "FW2C", "GG3Q", "GG3V", "FQY8", "FTPF"},
  /* iMac16,1       */ {"GH34", "GQ6K", "GQ6L", "GVYR", "GDF9", "GQ6F", "GQ6G", "GVYQ", "GH32", "GH36", "GQ6H", "GQ6J", "GVYV", "GDF7", "GDF8", "GQ6C", "GQ6D", "GVYT", "GPX5", "GPX6", "GPX7", "GPXC", "GPXD", "GPXF", "GPX3", "GPX4", "GXMK", "GPX8", "GPX9", "GXML", "H1WR", "HYGQ", "HQ9W", "H2KW", "HHMG", "GF1L", "GF1M", "GF1K", "H0N6", "H1DX", "J0DJ", "J0DH", "J0DG", "H8KX", "GG77", "GG79", "GG7D", "H0P6", "H1DY", "HQ9V", "HQ9T", "H1F2", "H1F1", "H25M"},
  /* iMac16,2       */ {"GQRY", "GQT0", "GQT1", "GPXJ", "GPXK", "GPXL", "GQRW", "GQRX", "GXMM", "GPXG", "GPXH", "GXMN", "GQT4", "GQT5", "GQT6", "GPXP", "GPXQ", "GPXR", "GQT2", "GQT3", "GXMP", "GPXM", "GPXN", "GXMQ"},
  /* iMac17,1       */ {"GPF7", "GPF8", "GPF3", "GPF4", "GTL1", "GTL2", "GPJ8", "GPJD", "GPDY", "GPF0", "GTL3", "GTL4", "GPJF", "GPJH", "GPJ9", "GPJJ", "GPJC", "GPJG"},
  /* iMac18,1       */ {"H69F", "H668"},
  /* iMac18,2       */ {"J0DX", "J0DY", "J0F0", "J0F1", "HNWJ", "HNWK", "J0RY", "J0T1", "HNWL", "HNWM", "HNWN", "HNWP"},
  /* iMac18,3       */ {"J0PG", "J0PH", "J0PJ", "J0PC", "J0PD", "J0PF", "HX77", "HX78", "HX79", "HX7C", "HX7D", "HX7F", "HNL6", "HNL7", "HNL8"},
  /* iMac19,1       */ {"LNV9", "KDP0"},
  /* iMac19,2       */ {"KGQG"},
  /* iMac4,1        */ {""},
  /* iMac4,2        */ {""},
  /* iMac5,1        */ {""},
  /* iMac5,2        */ {""},
  /* iMac6,1        */ {""},
  /* iMac7,1        */ {""},
  /* iMac8,1        */ {""},
  /* iMac9,1        */ {""},
  /* iMacPro1,1     */ {"JG36", "JG3C", "JG3D", "JG38", "JG39", "JML3", "JMPY", "JMQ0", "JML4", "JMQ1", "JMQ2", "J806", "J807", "J808", "J80H", "J80J", "J80M", "J803", "J804", "J805", "J809", "J80D", "J80F"},
};

#define APPLE_MODEL_YEAR_MAX 2
static uint32_t AppleModelYear[][APPLE_MODEL_YEAR_MAX] = {
  /* MacBook1,1     */ {2006},
  /* MacBook10,1    */ {2017},
  /* MacBook2,1     */ {2006, 2007},
  /* MacBook3,1     */ {2007},
  /* MacBook4,1     */ {2008},
  /* MacBook5,1     */ {2008},
  /* MacBook5,2     */ {2009},
  /* MacBook6,1     */ {2009},
  /* MacBook7,1     */ {2010},
  /* MacBook8,1     */ {2015},
  /* MacBook9,1     */ {2016},
  /* MacBookAir1,1  */ {2008},
  /* MacBookAir2,1  */ {2009},
  /* MacBookAir3,1  */ {2010},
  /* MacBookAir3,2  */ {2010},
  /* MacBookAir4,1  */ {2011},
  /* MacBookAir4,2  */ {2011},
  /* MacBookAir5,1  */ {2012},
  /* MacBookAir5,2  */ {2012},
  /* MacBookAir6,1  */ {2013, 2014},
  /* MacBookAir6,2  */ {2013, 2014},
  /* MacBookAir7,1  */ {2015},
  /* MacBookAir7,2  */ {2015, 2017},
  /* MacBookAir8,1  */ {2018},
  /* MacBookAir8,2  */ {2019},
  /* MacBookPro1,1  */ {2006},
  /* MacBookPro1,2  */ {2006},
  /* MacBookPro10,1 */ {2012, 2013},
  /* MacBookPro10,2 */ {2012, 2013},
  /* MacBookPro11,1 */ {2013, 2014},
  /* MacBookPro11,2 */ {2014},
  /* MacBookPro11,3 */ {2013},
  /* MacBookPro11,4 */ {2015},
  /* MacBookPro11,5 */ {2015},
  /* MacBookPro12,1 */ {2015},
  /* MacBookPro13,1 */ {2016},
  /* MacBookPro13,2 */ {2016},
  /* MacBookPro13,3 */ {2016},
  /* MacBookPro14,1 */ {2017},
  /* MacBookPro14,2 */ {2017},
  /* MacBookPro14,3 */ {2017},
  /* MacBookPro15,1 */ {2018},
  /* MacBookPro15,2 */ {2018, 2019},
  /* MacBookPro15,3 */ {2019},
  /* MacBookPro15,4 */ {2019},
  /* MacBookPro2,1  */ {2006},
  /* MacBookPro2,2  */ {2006},
  /* MacBookPro3,1  */ {2007},
  /* MacBookPro4,1  */ {2008},
  /* MacBookPro5,1  */ {2008},
  /* MacBookPro5,2  */ {2009},
  /* MacBookPro5,3  */ {2009},
  /* MacBookPro5,4  */ {2009},
  /* MacBookPro5,5  */ {2009},
  /* MacBookPro6,1  */ {2010},
  /* MacBookPro6,2  */ {2010},
  /* MacBookPro7,1  */ {2010},
  /* MacBookPro8,1  */ {2011},
  /* MacBookPro8,2  */ {2011},
  /* MacBookPro8,3  */ {2011},
  /* MacBookPro9,1  */ {2012},
  /* MacBookPro9,2  */ {2012},
  /* MacPro1,1      */ {2006},
  /* MacPro2,1      */ {2008},
  /* MacPro3,1      */ {2008},
  /* MacPro4,1      */ {2009},
  /* MacPro5,1      */ {2010, 2012},
  /* MacPro6,1      */ {2013},
  /* MacPro7,1      */ {2019},
  /* Macmini1,1     */ {2006},
  /* Macmini2,1     */ {2007},
  /* Macmini3,1     */ {2009},
  /* Macmini4,1     */ {2010},
  /* Macmini5,1     */ {2011},
  /* Macmini5,2     */ {2011},
  /* Macmini5,3     */ {2011},
  /* Macmini6,1     */ {2012},
  /* Macmini6,2     */ {2012},
  /* Macmini7,1     */ {2014},
  /* Macmini8,1     */ {2018},
  /* Xserve1,1      */ {2006},
  /* Xserve2,1      */ {2008},
  /* Xserve3,1      */ {2009},
  /* iMac10,1       */ {2009},
  /* iMac11,1       */ {2009},
  /* iMac11,2       */ {2010},
  /* iMac11,3       */ {2010},
  /* iMac12,1       */ {2011},
  /* iMac12,2       */ {2011},
  /* iMac13,1       */ {2012, 2013},
  /* iMac13,2       */ {2012},
  /* iMac13,3       */ {2013},
  /* iMac14,1       */ {2013},
  /* iMac14,2       */ {2013},
  /* iMac14,3       */ {2013},
  /* iMac14,4       */ {2014},
  /* iMac15,1       */ {2014, 2015},
  /* iMac16,1       */ {2015},
  /* iMac16,2       */ {2015},
  /* iMac17,1       */ {2015},
  /* iMac18,1       */ {2017},
  /* iMac18,2       */ {2017},
  /* iMac18,3       */ {2017},
  /* iMac19,1       */ {2019},
  /* iMac19,2       */ {2019},
  /* iMac4,1        */ {2006},
  /* iMac4,2        */ {2006},
  /* iMac5,1        */ {2006},
  /* iMac5,2        */ {2006},
  /* iMac6,1        */ {2007},
  /* iMac7,1        */ {2007},
  /* iMac8,1        */ {2008},
  /* iMac9,1        */ {2009},
  /* iMacPro1,1     */ {2017},
};

static uint32_t ApplePreferredModelYear[] = {
  /* MacBook1,1     */ 0,
  /* MacBook10,1    */ 0,
  /* MacBook2,1     */ 0,
  /* MacBook3,1     */ 0,
  /* MacBook4,1     */ 0,
  /* MacBook5,1     */ 0,
  /* MacBook5,2     */ 0,
  /* MacBook6,1     */ 0,
  /* MacBook7,1     */ 0,
  /* MacBook8,1     */ 0,
  /* MacBook9,1     */ 0,
  /* MacBookAir1,1  */ 0,
  /* MacBookAir2,1  */ 0,
  /* MacBookAir3,1  */ 0,
  /* MacBookAir3,2  */ 0,
  /* MacBookAir4,1  */ 0,
  /* MacBookAir4,2  */ 0,
  /* MacBookAir5,1  */ 0,
  /* MacBookAir5,2  */ 0,
  /* MacBookAir6,1  */ 0,
  /* MacBookAir6,2  */ 0,
  /* MacBookAir7,1  */ 0,
  /* MacBookAir7,2  */ 0,
  /* MacBookAir8,1  */ 0,
  /* MacBookAir8,2  */ 0,
  /* MacBookPro1,1  */ 0,
  /* MacBookPro1,2  */ 0,
  /* MacBookPro10,1 */ 0,
  /* MacBookPro10,2 */ 0,
  /* MacBookPro11,1 */ 0,
  /* MacBookPro11,2 */ 0,
  /* MacBookPro11,3 */ 0,
  /* MacBookPro11,4 */ 0,
  /* MacBookPro11,5 */ 0,
  /* MacBookPro12,1 */ 0,
  /* MacBookPro13,1 */ 0,
  /* MacBookPro13,2 */ 0,
  /* MacBookPro13,3 */ 0,
  /* MacBookPro14,1 */ 0,
  /* MacBookPro14,2 */ 0,
  /* MacBookPro14,3 */ 0,
  /* MacBookPro15,1 */ 0,
  /* MacBookPro15,2 */ 0,
  /* MacBookPro15,3 */ 0,
  /* MacBookPro15,4 */ 0,
  /* MacBookPro2,1  */ 0,
  /* MacBookPro2,2  */ 0,
  /* MacBookPro3,1  */ 0,
  /* MacBookPro4,1  */ 0,
  /* MacBookPro5,1  */ 0,
  /* MacBookPro5,2  */ 0,
  /* MacBookPro5,3  */ 0,
  /* MacBookPro5,4  */ 0,
  /* MacBookPro5,5  */ 0,
  /* MacBookPro6,1  */ 0,
  /* MacBookPro6,2  */ 0,
  /* MacBookPro7,1  */ 0,
  /* MacBookPro8,1  */ 0,
  /* MacBookPro8,2  */ 0,
  /* MacBookPro8,3  */ 0,
  /* MacBookPro9,1  */ 0,
  /* MacBookPro9,2  */ 0,
  /* MacPro1,1      */ 0,
  /* MacPro2,1      */ 0,
  /* MacPro3,1      */ 0,
  /* MacPro4,1      */ 0,
  /* MacPro5,1      */ 2012,
  /* MacPro6,1      */ 0,
  /* MacPro7,1      */ 0,
  /* Macmini1,1     */ 0,
  /* Macmini2,1     */ 0,
  /* Macmini3,1     */ 0,
  /* Macmini4,1     */ 0,
  /* Macmini5,1     */ 0,
  /* Macmini5,2     */ 0,
  /* Macmini5,3     */ 0,
  /* Macmini6,1     */ 0,
  /* Macmini6,2     */ 0,
  /* Macmini7,1     */ 0,
  /* Macmini8,1     */ 0,
  /* Xserve1,1      */ 0,
  /* Xserve2,1      */ 0,
  /* Xserve3,1      */ 0,
  /* iMac10,1       */ 0,
  /* iMac11,1       */ 0,
  /* iMac11,2       */ 0,
  /* iMac11,3       */ 0,
  /* iMac12,1       */ 0,
  /* iMac12,2       */ 0,
  /* iMac13,1       */ 0,
  /* iMac13,2       */ 0,
  /* iMac13,3       */ 0,
  /* iMac14,1       */ 0,
  /* iMac14,2       */ 0,
  /* iMac14,3       */ 0,
  /* iMac14,4       */ 0,
  /* iMac15,1       */ 0,
  /* iMac16,1       */ 0,
  /* iMac16,2       */ 0,
  /* iMac17,1       */ 0,
  /* iMac18,1       */ 0,
  /* iMac18,2       */ 0,
  /* iMac18,3       */ 0,
  /* iMac19,1       */ 0,
  /* iMac19,2       */ 0,
  /* iMac4,1        */ 0,
  /* iMac4,2        */ 0,
  /* iMac5,1        */ 0,
  /* iMac5,2        */ 0,
  /* iMac6,1        */ 0,
  /* iMac7,1        */ 0,
  /* iMac8,1        */ 0,
  /* iMac9,1        */ 0,
  /* iMacPro1,1     */ 0,
};

#endif // GENSERIAL_MODELINFO_AUTOGEN_H
